### ISSUE TITLE
Can't resolve 2.11.x

### ISSUE THREAD

**Issue by lgiorda** [sfxcode/simple-mongo#3]
Docs say 2.11.x is supported...but it cannot be found:

![image](https://user-images.githubusercontent.com/239604/36363461-27df57d8-14f2-11e8-8c01-8128a31553c3.png)

**Comment by sfxcode** [comment]
Add following lines to your build.sbt:

```
resolvers += "sxfcode Bintray Repo" at "https://dl.bintray.com/sfxcode/maven/"

libraryDependencies += "com.sfxcode.nosql" %% "simple-mongo" % "1.0.4"
```
